kind: ConfigMap
apiVersion: v1
metadata:
  name: chaskiq-postgres
  namespace: {{ .Release.Namespace }}
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: chaskiq
  POSTGRES_PASSWORD: passw0rd
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: chaskiq
  namespace: {{ .Release.Namespace }}
data:
  HOST: "https://{{ .Values.config.domain }}"
  WS: "wss://{{ .Values.config.domain }}/cable"
  DATABASE_URL: "postgresql://postgres:passw0rd@chaskiq-postgres.{{ .Release.Namespace }}:5432/chaskiq"
  REDIS_URL: "redis://chaskiq-redis.{{ .Release.Namespace }}:6379/0"
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: 'true'
  RAILS_SERVE_STATIC_FILES: 'true'
  LANG: en_US.UTF-8
  {{- with .Values.config.account }}
    {{ toYaml . | nindent 2 }}
  {{- end }}

  {{- with .Values.config.storage }}
    {{ toYaml . | nindent 2 }}
  {{- end }}

  {{- with .Values.config.email }}
    {{ toYaml . | nindent 2 }}
  {{- end }}


