kind: Deployment
apiVersion: apps/v1
metadata:
  name: chaskiq
  namespace: {{ .Release.Namespace }}
  labels:
    app: chaskiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaskiq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chaskiq
    spec:
      {{- if eq .Values.config.storage.ACTIVE_STORAGE_SERVICE "local" }}
      volumes:
        - name: volume-07u2zb
          persistentVolumeClaim:
            claimName: chaskiq-data
      {{- end }}
      containers:
        - name: chaskiq
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          command:
            - bundle
          args:
            - exec
            - rails
            - s
          ports:
            - name: https-web
              containerPort: 3000
              protocol: TCP
          env:
            - name: ACTIVE_STORAGE_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: ACTIVE_STORAGE_SERVICE
            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: ADMIN_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: AWS_S3_BUCKET
            - name: AWS_S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: AWS_S3_REGION
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: AWS_SECRET_ACCESS_KEY
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: DATABASE_URL
            - name: DEFAULT_OUTGOING_EMAIL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: DEFAULT_OUTGOING_EMAIL_DOMAIN
            - name: DEFAULT_SENDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: DEFAULT_SENDER_EMAIL
            - name: LANG
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: LANG
            - name: LOCAL_STORAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: LOCAL_STORAGE_PATH
            - name: RACK_ENV
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: RACK_ENV
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: RAILS_ENV
            - name: RAILS_LOG_TO_STDOUT
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: RAILS_LOG_TO_STDOUT
            - name: RAILS_SERVE_STATIC_FILES
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: RAILS_SERVE_STATIC_FILES
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: REDIS_URL
            - name: SECRET_KEY_BASE
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: SECRET_KEY_BASE
            - name: SMTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: SMTP_ADDRESS
            - name: SMTP_DELIVERY_METHOD
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: SMTP_DELIVERY_METHOD
            - name: SMTP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: SMTP_PASSWORD
            - name: SMTP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: SMTP_USERNAME
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: HOST
            - name: WS
              valueFrom:
                configMapKeyRef:
                  name: chaskiq
                  key: WS
          resources: {}
          {{- if eq .Values.config.storage.ACTIVE_STORAGE_SERVICE "local" }}
          volumeMounts:
            - name: volume-07u2zb
              mountPath: /usr/src/app/local_storage
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{ - with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{ - end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
{{- if eq .Values.config.storage.ACTIVE_STORAGE_SERVICE "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chaskiq-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storage.STORAGE_CLASS }}
  resources:
    requests:
      storage: 10Gi
{{- end }}