kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: chaskiq-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: chaskiq-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaskiq-postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chaskiq-postgres
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      containers:
        - name: container-sjucti
          image: postgres
          ports:
            - name: tcp-5432
              containerPort: 5432
              protocol: TCP
          env:
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: chaskiq-postgres
                  key: PGDATA
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: chaskiq-postgres
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: chaskiq-postgres
                  key: POSTGRES_PASSWORD
          resources: {}
          volumeMounts:
            - name: chaskiq-postgres-data
              mountPath: /var/lib/postgresql/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: chaskiq-postgres-data
        namespace: chaskiq
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: {{ .Values.config.storage.STORAGE_CLASS }}
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: chaskiq-postgres
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: chaskiq-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: chaskiq-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaskiq-redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chaskiq-redis
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      containers:
        - name: container-uiip9u
          image: redis
          ports:
            - name: tcp-6379
              containerPort: 6379
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: chaskiq-redis
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: chaskiq-redis-data
        namespace: chaskiq
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: {{ .Values.config.storage.STORAGE_CLASS }}
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: chaskiq-redis
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
---
kind: Service
apiVersion: v1
metadata:
  name: chaskiq-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: chaskiq-postgres
spec:
  ports:
    - name: tcp-5432
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: chaskiq-postgres
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
---
kind: Service
apiVersion: v1
metadata:
  name: chaskiq-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: chaskiq-redis
spec:
  ports:
    - name: tcp-6379
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: chaskiq-redis
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack